# Generated by Django 3.2.4 on 2021-07-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.CharField(max_length=10),
        ),
    ]
